### PR TITLE
Global change: Convert ExternalRef to ProtocolRef. OCECDR-4551

### PR DESCRIPTION
**Pull request by venglisch**
The global change ran in production.

### CODE REVIEW

**Comment by bkline** [comment]
I'll approve this if you want, but I've been avoiding checking in one-off global change scripts ever since Bryan asked us to prune scripts which will never be run again (like one-off global change scripts) from the repositories. 😃

**Comment by venglisch** [comment]
I understand Bryan's reasoning and I agree with the try-to-avoid-cruft approach but a repository is also a type of knowledge base, in my opinion.  It helps me get started or avoid pitfalls already addressed when I have a sample from a previous global run to look at, especially when there is some time before I have to write the next global change request.  Other people may remember every line of code they've written but I don't. :-) 
If you all feel very strongly about keeping one-off scripts out of the repository I'll find another place to store my code but it seems silly to me having to maintain multiple repositories.

**Comment by venglisch** [comment]
Are you referring to this commented-out line in the "select()" method?
#self.__doc_ids = [ 62902, 62707 ]

**Comment by bkline** [comment]
> Are you referring to this commented-out line in the "select()" method?
> #self.__doc_ids = [ 62902, 62707 ]

No, you've got an argument with document IDs passed into the constructor, and it's not obvious from looking at that constructor that the value passed in for that argument is going to be ignored.

**Comment by venglisch** [comment]
I did not change any of that.  It was part of the template OneOffGlobalTemplate.py I used.  We should probably change the template.

**Comment by bkline** [comment]
> I did not change any of that. It was part of the template OneOffGlobalTemplate.py I used. We should probably change the template.

We can always change the template, but the template didn't ignore the `doc_ids` argument passed into the constructor. It's OK to leave stuff like that hanging around if you're going to throw away the script after its only use. But if you want to preserve the script as an example to remind us how to handle specific types of global change requests in the future (in a way that the template doesn't already do), then you don't want to leave any confusing parts you've copied from the template but which leave us wondering when we come back to it "why is this argument being passed into the constructor?" I actually like the goal you have of preserving examples of different types of global change (and I think Bryan would approve as well). I'm just trying to be as rigorous as he would be in making sure we don't just try to achieve the goal by going back to the practice of building the pile back up of "scripts we've run in the past". Ideally, we'd enhance the template to add more comments about how to handle different requirements. If that's not sufficient, because we want a separate template for a requirement that's so completely different than what the template's doing, then let's capture that in a second template, using a descriptive name representing the techniques we're trying to remember, rather than a name tied to a specific job (making it hard to remember which example script to look at for a particular technique). It looks from this example that the difference you're trying to capture would be the use of an SQL query instead of a list in code to identify which documents to process for the job. One way to do that would be to modify the existing template to accept an argument in the constructor which is optional (perhaps using the `nargs="*"` option for `add_argument()`), representing a sequence of documents if passed when the script is invoked. The constructor would use the documents identified on the command line if present; otherwise it would fall back on the default of a SQL query. That approach shows how to combine the two approaches in a single script, using database logic by default, but allowing a test invocation to cherry-pick documents. What it *wouldn't* have is an argument passed into the constructor which is ignored, confusing us when we come back to use what we've saved in the repository to remind us how to do global changes.

Am I making any sense at all, or am I just being annoying? 🤔

**Comment by bkline** [comment]
It took me a _long_ time to do the work of pruning the repository Bryan asked us to do (and you did some of that work yourself). That's part of why I'm being so frustratingly persistent. 😅

**Comment by venglisch** [comment]
> It took me a _long_ time to do the work of pruning the repository Bryan asked us to do 

You're right. Keeping the script would only be for my personal benefit.  I'll revoke this PR.

**Pull request closed without merging**
